---
title: "Lists - In Class Exercises"
author: "Dr. Shoemaker"
date: "DATA 2401"
output: html_document

---

# Exercises: 

Make a list that contains the information on a single playing card. Suit, face, and value. 

```{r}
single_playing_card <- list (
  suit = c("diamonds"),
  face = c("jacks"),
  value = c(13)
)

single_playing_card

```


Make a second list where each element contains all the options for suit, face, and value, respectively. 

```{r}
playing_card_with_options <- list (
  suit = c("spades", "clubs", "hearts", "diamonds"),
  face = c("kings" ,"queens", "jacks"),
  value = c(11,12,13)
)

playing_card_with_options


```


If `Newlist <- list(a=1:10, b="Good morning", c="Hi")`, write an R statement that will add 1 to each element of the first vector in Newlist.

```{r}
Newlist <- list(a=1:10, b="Good morning", c="Hi")
Newlist$a <- Newlist$a + 1
Newlist


```

If `b <- list(a=1:10, c="Hello", d="AA")`, write an R expression that will give all elements of the first vector of b, except the second, and write another that returns only elements of `a` that are greater than 7.

```{r}
b <- list(a=1:10, c="Hello", d="AA")
b$a[-2]

condition <- (b$a > 7)
b$a[condition]

```

Let `x <- list(a=5:10, c="Hello", d="AA")`, write an R statement to add a new item z = "NewItem" to the list x.

```{r}
x <- list(a=5:10, c="Hello", d="AA")
x$z = "NewItem"
x

```
